# Generated by Django 2.0.3 on 2018-03-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('3', '중요'), ('2', '보통'), ('1', '낮음')], default='2', max_length=1),
        ),
    ]
